### ISSUE TITLE
url ending in newline no longer work

### ISSUE THREAD

**Issue by glycerine** [pquerna/otp#17]
I think the #10 fix made urls ending in newline no longer function, so I started getting crashes when I updated to the most recent otp.  For backwards compatibility, it might be nice to throw in a strings.TrimWhite() around the received url before parsing it.

~~~
package main

import (
	"fmt"
	"github.com/pquerna/otp"
	"github.com/pquerna/otp/totp"
	"time"
)

func main() {
	w, err := otp.NewKeyFromURL(`otpauth://totp/Example:alice@google.com?secret=JBSWY3DPEHPK3PXP
`)
	panicOn(err)
	sec := w.Secret()
	fmt.Printf("sec = '%v'\n", sec)
	code, err := totp.GenerateCode(sec, time.Now())
	panicOn(err)
	fmt.Printf("code = '%#v'\n", code)
}

func panicOn(err error) {
	if err != nil {
		panic(err)
	}
}
~~~
result
~~~
Compilation started at Sun Aug  6 17:08:27

go run min.go
sec = 'JBSWY3DPEHPK3PXP
'
panic: Decoding of secret as base32 failed.

goroutine 1 [running]:
main.panicOn(0x11581a0, 0xc42000e5f0)
    /Users/jaten/min.go:23 +0x4a
main.main()
    /Users/jaten/min.go:17 +0x187
exit status 2

Compilation exited abnormally with code 1 at Sun Aug  6 17:08:27
~~~

**Comment by pquerna** [comment]
Thanks for the report, #18 should fix this.
